import type { Metadata } from 'next'
import Link from 'next/link'
import { FeatherSparkleLogo, ChevronLeft } from '@/components/icons'

export const metadata: Metadata = {
  title: 'Terms of Service — Free Essay Scorer',
  description: 'Terms of Service for the Free Essay Scorer tool.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-admitly-cream">
      <header className="h-14 border-b border-admitly-black/6 bg-white flex items-center px-5">
        <Link href="/" className="flex items-center gap-2.5 group">
          <ChevronLeft size={18} className="text-admitly-black/40 group-hover:text-admitly-black transition-colors" />
          <FeatherSparkleLogo size={30} />
          <span className="font-display font-extrabold text-[18px] leading-none text-admitly-black tracking-[-0.025em]">
            Free Essay Scorer<span className="text-fes-blue">.</span>
          </span>
        </Link>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-10 sm:py-14">
        <p className="text-xs font-black tracking-[0.18em] text-fes-blue uppercase mb-3">Legal</p>
        <h1 className="font-display text-3xl sm:text-5xl font-black tracking-[-0.035em] text-admitly-black leading-[1] mb-3">
          Terms of Service<span className="text-fes-blue">.</span>
        </h1>
        <p className="text-sm text-admitly-black/50 mb-10">Last updated: April 2026</p>

        <div className="prose-content space-y-8 text-sm sm:text-[15px] text-admitly-black/80 leading-relaxed">

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">1. Acceptance of these terms</h2>
            <p>These Terms of Service (the &ldquo;Terms&rdquo;) form a binding legal agreement between you (&ldquo;you,&rdquo; &ldquo;your&rdquo;) and Free Essay Scorer (&ldquo;FES,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our&rdquo;). By accessing or using the FES website, tools, or services (collectively, the &ldquo;Service&rdquo;), you agree to be bound by these Terms. If you do not agree, do not use the Service.</p>
            <p className="mt-3">We may update these Terms at any time, in our sole discretion. Material changes will be reflected in the &ldquo;Last updated&rdquo; date above. Your continued use of the Service after changes constitutes acceptance of the revised Terms. We are not obligated to notify you individually of updates.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">2. What the Service is</h2>
            <p>FES is an automated, AI-assisted tool that provides feedback on college admissions essay drafts. You may use up to three analyses per calendar day per browser, across three publicly available tools: Hook Analyzer, Cliché Detector, and AI Check. Additional premium tools may be offered to registered users. FES is operated as a top-of-funnel product for Admitly, a separate admissions consulting service, but use of FES does not require an Admitly account.</p>
            <p className="mt-3">FES is a software product, not professional advice. Feedback generated by the Service is informational only and is not a substitute for guidance from teachers, counselors, admissions officers, or other qualified professionals. We do not guarantee any particular admissions outcome.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">3. Eligibility and accounts</h2>
            <p>You must be at least 13 years old to use the Service. If you are under the age of majority in your jurisdiction (typically 18), you represent that a parent or legal guardian has read these Terms and consents to your use. You are responsible for all activity associated with your browser session.</p>
            <p className="mt-3">If you submit an email address to us (for example, to request free Admitly credits), you represent that the address belongs to you and that the information you provide is accurate. We may refuse, suspend, or terminate access to the Service for any reason, including suspected abuse, automated access, or violation of these Terms, without notice and without liability.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">4. How your essay text is processed</h2>
            <p>When you submit an essay, the text you paste is transmitted to <span className="font-bold text-admitly-black">OpenAI&apos;s API</span> for processing. OpenAI is an independent third party operating under its own terms and data policies. We do not control OpenAI&apos;s handling of your text and are not responsible for their practices, security, or availability.</p>
            <p className="mt-3">FES does not persistently store the essay text you submit. Feedback is generated in real time and is not saved to our servers by default. That said, we log anonymous operational metadata (e.g. which tool was used, whether the request succeeded, the qualitative tier of the result) as described in the Privacy Policy.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">5. Your content and license</h2>
            <p>You retain all right, title, and interest in the essay text you submit. You represent and warrant that you own or have the necessary rights to submit the content and that it does not infringe any third-party rights.</p>
            <p className="mt-3">By submitting content, you grant us a limited, non-exclusive, royalty-free license to process, transmit to third-party AI providers, and temporarily cache your content solely for the purpose of generating the feedback you requested and operating the Service. This license ends when processing is complete.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">6. Acceptable use</h2>
            <p>You agree NOT to:</p>
            <ul className="list-disc pl-5 space-y-1.5 mt-2">
              <li>Submit content you do not have the right to share, or content that infringes any copyright, trademark, or other intellectual property right.</li>
              <li>Submit content involving minors in a sexual, threatening, exploitative, or otherwise harmful context.</li>
              <li>Submit content that is illegal, defamatory, harassing, hateful, threatening, or that promotes violence or discrimination.</li>
              <li>Attempt to extract training data, system prompts, or internal configuration of the Service or any AI provider it integrates with.</li>
              <li>Automate, scrape, or otherwise programmatically access the Service beyond normal interactive use by a single human user.</li>
              <li>Circumvent, attempt to circumvent, or interfere with the per-browser daily quota or any other technical or access control.</li>
              <li>Reverse-engineer, decompile, or otherwise attempt to derive source code from the Service.</li>
              <li>Use the Service to build or benchmark a competing product.</li>
              <li>Interfere with the operation of the Service or the servers or networks that host it.</li>
              <li>Submit content that contains viruses, malware, or other harmful code.</li>
            </ul>
            <p className="mt-3">We reserve the right to investigate and take appropriate action against any user who, in our sole judgment, violates this section, including removing content, suspending access, and cooperating with law enforcement.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">7. Intellectual property</h2>
            <p>The Service, including its design, code, trademarks, logos (including the Free Essay Scorer name and feather mark), written content, and organization, is owned by us or our licensors and is protected by copyright, trademark, and other laws. Nothing in these Terms grants you any right in or to our intellectual property except the limited right to use the Service as expressly permitted here.</p>
            <p className="mt-3">If you believe content accessible through the Service infringes your copyright, please send a notice including the information required under applicable law (e.g. 17 U.S.C. § 512(c)(3) in the United States) to the contact address below.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">8. Third-party services</h2>
            <p>The Service integrates with or links to third-party services including, without limitation, OpenAI (for AI processing) and Admitly (for premium credit fulfillment). We are not responsible for the availability, content, terms, privacy practices, or security of any third-party service. Your interactions with third-party services are governed by their own terms and policies.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">9. No warranty — service provided &ldquo;as is&rdquo;</h2>
            <p>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE,&rdquo; WITHOUT ANY WARRANTY OF ANY KIND, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. WE SPECIFICALLY DISCLAIM ALL WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, COMPLETENESS, AND FREEDOM FROM COMPUTER VIRUSES OR OTHER HARMFUL CODE.</p>
            <p className="mt-3">WE DO NOT WARRANT THAT: (A) THE SERVICE WILL MEET YOUR REQUIREMENTS; (B) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; (C) ANY INFORMATION OR FEEDBACK GENERATED BY THE SERVICE WILL BE ACCURATE OR RELIABLE; OR (D) ANY PARTICULAR ADMISSIONS OUTCOME WILL RESULT FROM USE OF THE SERVICE. YOU ASSUME ALL RISK AND RESPONSIBILITY FOR ANY DECISIONS YOU MAKE BASED ON THE FEEDBACK.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">10. Limitation of liability</h2>
            <p>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL WE, OUR AFFILIATES, OR OUR OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, REVENUE, DATA, GOODWILL, ADMISSIONS OUTCOMES, EDUCATIONAL OPPORTUNITIES, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
            <p className="mt-3">OUR AGGREGATE LIABILITY TO YOU FOR ANY AND ALL CLAIMS ARISING OUT OF OR RELATED TO THE SERVICE WILL NOT EXCEED FIFTY U.S. DOLLARS (USD $50). SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU; IN SUCH CASES, OUR LIABILITY IS LIMITED TO THE MINIMUM EXTENT PERMITTED BY LAW.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">11. Indemnification</h2>
            <p>You agree to defend, indemnify, and hold harmless FES, its affiliates, and their respective officers, directors, employees, contractors, agents, licensors, and suppliers from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys&apos; fees) arising out of or related to: (a) your use of the Service; (b) any content you submit; (c) your violation of these Terms; or (d) your violation of any third-party right, including any intellectual property, privacy, or publicity right.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">12. Termination</h2>
            <p>We may suspend or terminate your access to the Service at any time, for any reason or no reason, with or without notice, and without liability. Upon termination, your right to use the Service ceases immediately. Sections that by their nature should survive termination (including sections 5, 7, 9–11, and 13–16) will survive.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">13. Governing law and venue</h2>
            <p>These Terms are governed by the laws of the Commonwealth of Pennsylvania, United States, without regard to conflict-of-laws principles. You agree that any action at law or in equity arising out of or relating to these Terms or the Service that is not subject to the arbitration provision below will be filed only in the state or federal courts located in Philadelphia, Pennsylvania, and you hereby consent and submit to the personal jurisdiction of those courts for the purposes of litigating any such action.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">14. Dispute resolution; arbitration; class-action waiver</h2>
            <p>Any dispute, claim, or controversy arising out of or relating to these Terms or the Service (each, a &ldquo;Dispute&rdquo;) will first be attempted to be resolved by informal good-faith negotiation, initiated by written notice to the contact address below. If the Dispute is not resolved within 60 days, it will be resolved exclusively through final and binding individual arbitration administered by a neutral arbitration provider mutually agreed upon by the parties, or, absent agreement, by JAMS under its then-current Streamlined Arbitration Rules. The arbitration will be conducted in English, in Philadelphia, Pennsylvania, or by remote proceedings at the arbitrator&apos;s discretion.</p>
            <p className="mt-3"><span className="font-bold text-admitly-black">YOU AND WE AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN AN INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION.</span> The arbitrator may not consolidate more than one person&apos;s claims and may not otherwise preside over any form of a representative or class proceeding. If this class-action waiver is held unenforceable, then the entire arbitration provision will be null and void, and the Dispute will proceed in court under section 13.</p>
            <p className="mt-3">Notwithstanding the above, either party may bring an individual action in small-claims court for qualifying disputes, and either party may seek injunctive or equitable relief in court to protect its intellectual property rights.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">15. Miscellaneous</h2>
            <ul className="list-disc pl-5 space-y-1.5 mt-2">
              <li><span className="font-bold">Entire agreement.</span> These Terms, together with the Privacy Policy, constitute the entire agreement between you and us regarding the Service and supersede all prior agreements on the subject.</li>
              <li><span className="font-bold">Severability.</span> If any provision of these Terms is held invalid or unenforceable, the remaining provisions will continue in full force and effect.</li>
              <li><span className="font-bold">No waiver.</span> Our failure to enforce any provision is not a waiver of our right to do so later.</li>
              <li><span className="font-bold">Assignment.</span> You may not assign these Terms without our prior written consent; we may assign them freely.</li>
              <li><span className="font-bold">Force majeure.</span> We are not liable for any failure or delay in performance due to causes beyond our reasonable control, including acts of God, war, internet outages, or third-party service failures.</li>
              <li><span className="font-bold">No agency.</span> No joint venture, partnership, employment, or agency relationship exists between you and us as a result of these Terms.</li>
              <li><span className="font-bold">Notices.</span> We may provide notices to you by posting on the Service or sending to the email address you provided. You must give notices to us as described in section 16.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-lg font-black text-admitly-black mb-2 tracking-tight">16. Contact</h2>
            <p>Questions, notices, or legal correspondence should be directed to <span className="font-bold text-admitly-black">support (at) freeessayscorer.com</span>.</p>
          </section>

        </div>

        <div className="mt-12 pt-6 border-t border-admitly-black/10 flex items-center justify-between text-xs text-admitly-black/50">
          <Link href="/" className="font-semibold hover:text-admitly-black transition-colors">← Back to Free Essay Scorer</Link>
          <Link href="/privacy" className="font-semibold hover:text-admitly-black transition-colors">Privacy Policy →</Link>
        </div>
      </main>
    </div>
  )
}
